name: build
on: [push, pull_request]
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: eefe957034753132d6ba53625fd0ddba319024481800c39a415e2410c64dd60b
        with:
          coverageCommand: npm run coverage
          coverageLocations: './coverage/clover.xml:clover'
          dubug: true
